# Site
name: "Lindsay Hill"
title: "Lindsay Hill"
description: "automation, networking, worklife"
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/favicon.ico'
url: 'https://lkhill.com/'
baseurl: ''
disqus: 'lkhill'
#mailchimp-list: ''
include: ["_pages",_redirects]
permalink: /:title/

# Authors
authors:
  lindsay:
    name: Lindsay
    display_name: Lindsay
    gravatar: fc3d5295f7b670886cdbabd7287d0b14
    github: LindsayHill
    email: lindsay.k.hill@gmail.com
    web: https://lkhill.com
    twitter: https://twitter.com/northlandboy
    description: "Network engineer, recovering Product Manager, occasional bike tourist."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-gist

feed:
  path: /feed/index.xml
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layout: archive
  layouts:
    year: year-archive
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
