# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:title/

# Setup
title:            'Lindsay Hill'
tagline:          'automation, networking, product management'
description:      'Technical posts on automation, network management, career and worklife'
url:              https://lkhill.com
baseurl:             /

author:
  name:           'Lindsay Hill'
  url:            https://twitter.com/northlandboy
  email:          lindsay.k.hill@gmail.com
  github:         LindsayHill
  twitter:        northlandboy

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/LindsayHill/lindsayhill.github.io

feed: 
  path: /feed/index.xml

# Gems
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
